_target_: src.models.template_lit.LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.cnn_16khz_marmosets.CNN_16KHz_Marmosets
  num_input: 1
  win_size_s: 0.03
  win_shift_s: 0.005
  sample_rate: ${sample_rate}
  num_channels: 128
  flatten_size: 4 
  selected_labels: ${data.data.selected_labels}
  lengths: ${data.data.lengths}
