# @package _global_

defaults:
  - override /hydra/launcher: dask

hydra:
  launcher:
    queue: "q_1day"
    walltime: "24:00:00"
    log_directory: ${hydra.sweep.dir}/dask-logs
    hostname: "'vcn*'"
